# Generated by Django 6.0.5 on 2026-05-23 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('pakistan', 'Pakistan'), ('asia', 'Asia'), ('europe', 'Europe'), ('middle_east', 'Middle East'), ('americas', 'Americas'), ('africa', 'Africa')], max_length=50)),
                ('description', models.TextField()),
                ('detail', models.TextField(blank=True)),
                ('image_url', models.URLField(max_length=500)),
                ('altitude', models.CharField(blank=True, max_length=100)),
                ('best_season', models.CharField(blank=True, max_length=100)),
                ('duration_days', models.IntegerField(default=5)),
                ('price_pkr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('num_passengers', models.IntegerField(default=1)),
                ('travel_date', models.DateField()),
                ('total_price_pkr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('special_notes', models.TextField(blank=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel.package')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
    ]
